<?php

namespace Icommerce\Scheduler\Block\Adminhtml\Operation\Edit\Tab;
class Details extends \Magento\Backend\Block\Widget\Form
{
    protected $help;
    protected $op;
    protected $reg;
    protected $yn;
    protected $email;
    public function _construct(\Magento\Backend\Block\Template\Context $context,
                               \Icommerce\Scheduler\Helper\Data $help,
                                \Icommerce\Scheduler\Model\Operation $op,
                               \Magento\Framework\Registry $registry,
                               \Magento\Config\Model\Config\Source\Yesno $yn,
                                \Magento\Email\Model\ResourceModel\Template\Collection $email,
                               array $data = [])
    {
        $this->op = $op;
        $this->help = $help;
        $this->reg = $registry;
        $this->yn = $yn;
        $this->email = $email;
        parent::_construct($context, $data); // TODO: Change the autogenerated stub
    }

    protected function _prepareForm()
    {
        $form = new \Magento\Framework\Data\Form();
        $this->setForm($form);

        $schedulerOperations = $this->help->getDefinedSchedulerOperations();
        $codeOptions = array('' => '');
        foreach ($schedulerOperations as $key => $value) {
            $codeOptions[$key] = $value['label'];
        }

        $allOperations = array('' => '');
        $operations = $this->op->getCollection()->getItems();
        $operations = array();
        foreach ($operations as $operation) {
            $allOperations[$operation->getId()] = isset($codeOptions[$operation->getCode()]) ? $codeOptions[$operation->getCode()] : $operation->getCode();
        }

        $actionforward = $this->getRequest()->getBeforeForwardInfo('action_name');
        $actionmethod = $this->getRequest()->getActionName();

        $general = $form->addFieldset('general_form', array('legend' => $this->__('Details')));

        $general->addField('code', 'select', array(
            'name'      => 'code',
            'label'     => __('Task'),
            'required'  => true,
            'options'   => $codeOptions,
        ));

//        $general->addField('name', 'text', array(
//            'name'      => 'name',
//            'label'     => Mage::helper('scheduler')->__('Name'),
//            'required'  => false,
//        ));

        /** @var $dependenceBlock Mage_Adminhtml_Block_Widget_Form_Element_Dependence */
        $dependenceBlock = $this->getLayout()->createBlock('\Icommerce\Block\Adminhtml\Widget\Form\Element\Dependence');
        $dependenceBlock->addFieldMap('code', 'code');
        $parameters = null;

        // add fields
        foreach ($schedulerOperations as $operationCode => $schedulerOperation) {
            if (isset($schedulerOperation['fields'])) {
                foreach ($schedulerOperation['fields'] as $fieldName => $fieldData) {
                    $elementId = $operationCode . '[' . $fieldName . ']';
                    $fieldType = (isset($fieldData['frontend_type']) ? $fieldData['frontend_type'] : 'text');

                    $config = array();
                    $config['label'] = (isset($fieldData['label']) ? $fieldData['label'] : '(label missing)');
                    $config['required'] = (isset($fieldData['required']) ? $fieldData['required'] : false);
                    $config['name'] = $elementId;

                    if ($fieldType == 'date') {
                        $config['image'] = $this->getSkinUrl('images/grid-cal.gif');
                        if (isset($fieldData['format'])) {
                            $config['format'] = $fieldData['format'];
                        } else {
                            $tz = new \Magento\Framework\Stdlib\DateTime\TimeZone();
                            $config['format'] = $tz->getDateFormatWithLongYear();
                        }

                        // This will be used to assess if the format conversion (to JS dateTime format) should also include time
                        if ($config['time'] = preg_match('/[Hms]/', $config['format'])) {
                            // Making the field a bit longer to allow time to display correctly
                            $config['style'] = 'width:130px;';
                        }
                    }

                    if (isset($fieldData['comment'])) {
                        $config['after_element_html'] = '<p class="note"><span>' . $fieldData['comment'] . '</span></p>';
                    }

                    if ($parameters == null) {
                        $parameters = $form->addFieldset('parameters', array('legend' => $this->__('Parameters')));
                    }

                    $field = $parameters->addField($elementId, $fieldType, $config);

                    if (isset($fieldData['source_model'])) {
                        $factoryName = (string)$fieldData['source_model'];
                        $method = false;

                        if (preg_match('/^([^:]+?)::([^:]+?)$/', $factoryName, $matches)) {
                            array_shift($matches);
                            list($factoryName, $method) = array_values($matches);
                        }

                        $sourceModel = $this->getLayout()->getBlockSingleton($factoryName);

                        if ($method) {
                            if ($fieldType == 'multiselect') {
                                $optionArray = $sourceModel->$method();
                            } else {
                                $optionArray = array();
                                foreach ($sourceModel->$method() as $value => $label) {
                                    $optionArray[] = array('label' => $label, 'value' => $value);
                                }
                            }
                        } else {
                            $optionArray = $sourceModel->toOptionArray($fieldType == 'multiselect');
                        }
                        $field->setValues($optionArray);
                    }

                    if (isset($fieldData['frontend_model'])) {
                        $fieldRenderer = $this->getLayout()->getBlockSingleton((string)$fieldData['frontend_model']);
                        $fieldRenderer->setForm($this);
                        $field->setRenderer($fieldRenderer);
                    }

                    $dependenceBlock->addFieldMap($elementId, $elementId);
                    $dependenceBlock->addFieldDependence($elementId, 'code', $operationCode);
                }
            }
        }

        if ($parameters != null) {
            $this->setChild('form_after', $dependenceBlock);
        }

        $general->addField('comment', 'textarea', array(
            'name'      => 'comment',
            'label'     => __('Comment'),
            'required'  => false,
        ));

        $general->addField('status', 'select', array(
            'name'      => 'status',
            'label'     => __('Status'),
            'required'  => true,
            'values'    => $this->help->getOperationStatusesOptionArray(true),
        ));

        $general->addField('save_history', 'multiselect', array(
            'name'      => 'save_history[]',
            'label'     => __('Save History for Status'),
            'values'    => $this->help->getHistoryStatusesMultiOptionArray(),
        ));

        $general->addField('url_override', 'text', array(
            'name'      => 'url_override',
            'label'     => __('Base URL if different from default'),
            'required'  => false,
        ));

        $authentication = $form->addFieldset('authentication_form', array('legend' => $this->__('HTTP Authentication')));

        $authentication->addField('authentication_type', 'select', array(
            'name'      => 'authentication_type',
            'label'     => __('Authentication Type'),
            'required'  => false,
            'values'    => $this->help->getAuthenticationTypes(),
        ));

        $authentication->addField('username', 'text', array(
            'name'      => 'username',
            'label'     => __('Username'),
            'required'  => false,
        ));

        $authentication->addField('password', 'password', array(
            'name'      => 'password',
            'label'     => __('Password'),
            'required'  => false,
            'after_element_html' => '<p class="note"><span>If trigger function requires 401 authentication, then specify type, username and password here</span></p>',
        ));

        $recurrence = $form->addFieldset('recurrence_form', array('legend' => $this->__('Recurrence Information')));

        $recurrence->addField('recurrence_info[frequency]', 'select', array(
            'name'      => 'recurrence_info[frequency]',
            'label'     => __('Frequency'),
            'values'    => $this->help->getOperationRecurrenceOptionArray('frequency'),
        ));

        $recurrence->addField('recurrence_info[n]', 'select', array(
            'name'      => 'recurrence_info[n]',
            'label'     => __('n'),
            'values'    => $this->help->getOperationRecurrenceOptionArray('n'),
        ));

        $recurrence->addField('recurrence_info[hour]', 'select', array(
            'name'      => 'recurrence_info[hour]',
            'label'     => __('Hour'),
            'values'    => $this->help->getOperationRecurrenceOptionArray('hour'),
        ));

        $recurrence->addField('recurrence_info[minute]', 'select', array(
            'name'      => 'recurrence_info[minute]',
            'label'     => __('Minute'),
            'values'    => $this->help->getOperationRecurrenceOptionArray('minute'),
        ));

        $recurrence->addField('recurrence_info[weekday]', 'select', array(
            'name'      => 'recurrence_info[weekday]',
            'label'     => __('Weekday'),
            'values'    => $this->help->getOperationRecurrenceOptionArray('weekday'),
        ));

        $recurrence->addField('recurrence_info[day]', 'select', array(
            'name'      => 'recurrence_info[day]',
            'label'     => __('Day'),
            'values'    => $this->help->getOperationRecurrenceOptionArray('day'),
        ));

        $recurrence->addField('recurrence_info[month]', 'select', array(
            'name'      => 'recurrence_info[month]',
            'label'     => __('Month'),
            'values'    => $this->help->getOperationRecurrenceOptionArray('month'),
        ));

        $rerun = $form->addFieldset('rerun_form', array('legend' => $this->__('Rerun task on failed status')));

        $rerun->addField('rerun', 'select', array(
            'name'      => 'rerun',
            'label'     => __('Enable'),
            'values'    => $this->yn->toOptionArray(),
        ));

        $rerun->addField('rerun_count', 'select', array(
            'name'      => 'rerun_count',
            'label'     => __('Rerun tries count'),
            'values'    => $this->help->getRerunCountOptionArray(),
        ));

        $master = $form->addFieldset('master_form', array('legend' => $this->__('Master Slave Dependency')));

        $master->addField('master_id', 'select', array(
            'name'      => 'master_id',
            'label'     => __('Master ID (if this is a slave)'),
            'values'    => $allOperations,
        ));

        $master->addField('master_order', 'text', array(
            'name'      => 'master_order',
            'label'     => __('Order'),
            'required'  => false,
        ));

        $email = $form->addFieldset('email_form', array('legend' => $this->__('Email')));

        $email->addField('email_enabled', 'select', array(
            'name'      => 'email_enabled',
            'label'     => __('Send Email'),
            'values'    => $this->yn->toOptionArray(),
        ));

        $email->addField('email_status', 'multiselect', array(
            'name'      => 'email_status[]',
            'label'     => __('Send Email for Status'),
            'values'    => $this->help->getHistoryStatusesMultiOptionArray(),
        ));

        $email->addField('email_template', 'select', array(
            'name'      => 'email_template',
            'label'     => __('Email Template'),
            'values'    => $this->email->toOptionArray(),
        ));

        $email->addField('email_sender', 'select', array(
            'name'      => 'email_sender',
            'label'     => __('Email Sender'),
            'values'    => $this->email->toOptionArray(),
        ));

        $email->addField('email_receiver', 'text', array(
            'name'      => 'email_receiver',
            'label'     => __('Email Recipients'),
            'required'  => false,
            'after_element_html' => '<p class="note"><span>Comma-separated.</span></p>',
        ));

        /** @var $operation Icommerce_Scheduler_Model_Operation */
        if ($operation = $this->reg->registry('operation_data')) {
            $data = $operation->getData();
            if ($operation->getRecurrenceInfo()) {
                foreach ($operation->getRecurrenceInfo() as $key => $value) {
                    $data['recurrence_info[' . $key . ']'] = $value;
                }
            }
            if ($operation->getCode() && $operation->getParameters()) {
                foreach ($operation->getParameters() as $key => $value) {
                    $data[$operation->getCode() . '[' . $key . ']'] = $value;
                }
            }

            if (!isset($data['save_history'])) {
                $statuses = $this->help->getHistoryStatusesOptionArray();
                $data['save_history'] = implode(',', array_keys($statuses));
            }

            $form->setValues($data);
        }

        return parent::_prepareForm();
    }
}